apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
    annotations: null

    name: axel-http
spec:
    routes:
        - kind: Rule
          match: Host(`{{ .Values.ingressroute.hostName }}`) && PathPrefix(`{{ .Values.ingressroute.pathPrefixPrefix }}/shs-broker`)
          middlewares:
              - name: ipwhitelist
              - name: redirect-https
          services:
              - kind: Service
                name: axel
                port: 8080
        - kind: Rule
          match: Host(`{{ .Values.ingressroute.hostName }}`) && PathPrefix(`{{ .Values.ingressroute.pathPrefixPrefix }}/riv-shs`)
          middlewares:
              - name: ipwhitelist
              - name: redirect-https
          services:
              - kind: Service
                name: axel
                port: 8080

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
    annotations: null
    labels:
        app.kubernetes.io/instance: axel-dev
    name: axel-https
    namespace: ntjp-dev
spec:
    routes:
        - kind: Rule
          match: Host(`{{ .Values.ingressroute.hostName }}`) && PathPrefix(`{{ .Values.ingressroute.pathPrefixPrefix }}/shs-broker`)
          middlewares:
              - name: ipwhitelist
              - name: stripprefix
          priority: 10
          services:
              - kind: Service
                name: axel-web
                passHostHeader: true
                port: 8080
                responseForwarding:
                    flushInterval: 1ms
                scheme: http
                sticky:
                    cookie:
                        httpOnly: true
                        name: cookie
                        sameSite: none
                        secure: true
                strategy: RoundRobin
                weight: 10
        - kind: Rule
          match: Host(`{{ .Values.ingressroute.hostName }}`) && PathPrefix(`{{ .Values.ingressroute.pathPrefixPrefix }}/riv-shs`)
          middlewares:
              - name: ipwhitelist
              - name: stripprefix
          priority: 10
          services:
              - kind: Service
                name: axel-web
                passHostHeader: true
                port: 8080
                responseForwarding:
                    flushInterval: 1ms
                scheme: http
                sticky:
                    cookie:
                        httpOnly: true
                        name: cookie
                        sameSite: none
                        secure: true
                strategy: RoundRobin
                weight: 10
    tls:
        domains:
            - main: dev.ntjp.se
        secretName: dev.ntjp.se-letsencrypt
