{{- $pathPrefix := trimAll "/" .Values.ingressroute.pathPrefix -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
    annotations: null
    labels:
        app.kubernetes.io/instance: {{ .Chart.Name }}
    name: axel-https
spec:
    routes:
        - kind: Rule
          match: Host(`{{ .Values.ingressroute.hostName }}`) && PathPrefix(`/{{ $pathPrefix }}/`)
          middlewares:
              - name: {{ .Chart.Name }}-ipwhitelist
              - name: {{ .Chart.Name }}-redirectwithslash
              - name: {{ .Chart.Name }}-stripprefix
          priority: 10
          services:
              - kind: Service
                name: axel
                passHostHeader: true
                port: 8080
                responseForwarding:
                    flushInterval: 1ms
                scheme: http
    tls:
        domains:
            - main: {{ .Values.ingressroute.hostName }}
        secretName: {{ .Values.ingressroute.hostName }}-letsencrypt
