apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
    annotations: null
    labels:
        app.kubernetes.io/instance: axel-dev
    name: axel-https
    namespace: ntjp-dev
spec:
    routes:
        - kind: Rule
          match: Host(`{{ .Values.ingressroute.hostName }}`) && PathPrefix(`{{ .Values.ingressroute.pathPrefixPrefix }}/`)
          middlewares:
              - name: ipwhitelist
              - name: stripprefix
          priority: 10
          services:
              - kind: Service
                name: axel
                passHostHeader: true
                port: 8080
                responseForwarding:
                    flushInterval: 1ms
                scheme: http
    tls:
        domains:
            - main: dev.ntjp.se
        secretName: dev.ntjp.se-letsencrypt
