{{- $pathPrefix := trimAll "/" .Values.ingressroute.pathPrefix -}}
{{- $defaultIpWhiteList := dict "sourceRange" (list "0.0.0.0/0")  -}} {{- /* allow all */ -}}
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  labels:
    app.kubernetes.io/instance: {{ .Chart.Name }}
  name: {{ .Chart.Name }}-ipwhitelist
spec:
  ipWhiteList: {{ .Values.ipWhiteList | default $defaultIpWhiteList | toYaml | nindent 8 }}

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  labels:
    app.kubernetes.io/instance: {{ .Chart.Name }}
  name: {{ .Chart.Name }}-stripprefix
spec:
  stripPrefix:
    prefixes:
    - /{{  $pathPrefix }}/

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  labels:
    app.kubernetes.io/instance: {{ .Chart.Name }}
  name: {{ .Chart.Name }}-redirectwithslash
spec:
  redirectRegex:
    regex: '^https?://([^/]*)/{{ $pathPrefix }}/([^/]*)$'
    replacement: 'https://${1}/{{ $pathPrefix }}/${2}/'
