{{- $pathPrefix := trimAll "/" .Values.ingressroute.pathPrefixPrefix -}}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
    labels:
        app.kubernetes.io/instance: {{ .Chart.Name }}
    name: ipwhitelist
spec:
    ipWhiteList:
        sourceRange:
            - 10.6.3.0/24 # Orange-VPN
            - 185.144.144.144/28 # NMT-VPN

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
    labels:
        app.kubernetes.io/instance: {{ .Chart.Name }}
    name: stripprefix
spec:
   stripPrefix:
        prefixes:
            - /{{  $pathPrefix }}/
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
    labels:
        app.kubernetes.io/instance: {{ .Chart.Name }}
    name: redirectwithslash
spec:
    redirectRegex:
        regex: '^https?://([^/]*)/{{ $pathPrefix }}/([^/]*)$'
        replacement: 'https://${1}/{{ $pathPrefix }}/${2}/'