apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.vip.name }}
spec:
  selector:
    app: axel
  type: ClusterIP
  ports:
    - port:  8082
      targetPort: 8082
      protocol: TCP
      name: http
    - port:  8080
      targetPort: 8080
      protocol: TCP
      name: web
