apiVersion: v1
kind: ConfigMap
metadata:
  name: axel-setenv
data:
  setenv.sh:
    export CATALINA_OPTS="$CATALINA_OPTS
        -Daxel.home=$AXEL_HOME
        -Dtak.db.login=$TAK_DB_LOGIN
        -Dtak.db.url=$TAK_DB_URL
        -Dtak.db.password=$TAK_DB_PASSWORD
        -DrsEndpoint=$RS_ENDPOINT
        -DproductServiceRestEndpoint=$PRODUCT_SERVICE_REST_ENDPOINT
        -Dlog4j.configuration=file:{{.Values.log4j.mount.mountPath}}
        -Dlog4j.configurationFile=file:{{.Values.log4j.mount.mountPath}}"



