# Default values for Axel.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
namespace: ntjp

deployment:
  axel:
    name: axel
  mongo:
    name: axel-mongodb

container:
  axel:
    image:
      name: axel
      pullPolicy: always
  mongo:
    image:
      name: mongodb
      pullPolicy: always

service:
  axel:
    type: ClusterIP
    port: 8082
  mongo:
    type: ClusterIP
    port: 27017

environment:
  axel:
    variables:
      config_maps:
        - axel-configmap-default
  mongo:
    # Nothing yet.


    