repository: docker.drift.inera.se/ntjp/
container:
  axel:
    image:
      pullPolicy: Always
      tag:

imagePullSecrets:
- name: regcred


ingressroute:
  hostName: base.env.url # This should be overridden and set to your environment's base name.
  pathPrefixPrefix: "/axel"

environment:
  axel:
    variables:
      _default_config_maps:
      - axel-configmap-default
      config_maps:
      # Nothing yet. Override to supply your own values.
      secrets:
      - axel-secrets
    secretVolumes:
      certs:
        secretName: axel-certs
        mountPath: /etc/axel/certs


resources: {}
