repository: docker.drift.inera.se/ntjp/

deployment:
  replicaCount: 1
  elasticGrokFilter: axel

container:
  axel:
    image:
      pullPolicy: Always
      tag: 

imagePullSecrets:
  - name: regcred

log4j:
  volume:
    name: axel-log4j-vol
    configMap:
      name: axel-log4j
      items:
        - key: log4j.xml
          path: log4j.xml
  mount:
    mountPath: /opt/log4j
    subPath: log4j.xml

tomcat_logging:
  volume:
    name: axel-logging-props-vol
    configMap:
      name: axel-logging-props
      items:
        - key: logging.properties
          path: logging.properties
  mount:
    mountPath: /usr/local/tomcat/conf
    subPath: logging.properties

setenv:
  volume:
    name: axel-setenv-vol
    configMap:
      name: axel-setenv
      items:
        - key: setenv.sh
          path: setenv.sh
  mount:
    mountPath: /usr/local/tomcat/bin
    subPath: setenv.sh


ingressroute:
  hostName: axel.localhost
  bksHostName: base.env.url # This should be overridden and set to your environment's base hostname.
  pathPrefix: "axel"

environment:
  axel:
    home: /usr/local/tomcat
    variables:
      _default_config_maps:
        - axel-configmap-default
      config_maps:
        # Nothing yet. Override to supply your own values.
      secrets:
        - axel-secrets
    secretVolumes:
      certs:
        secretName: axel-certs
        mountPath: /etc/axel/certs


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi