repository: docker.drift.inera.se/ntjp/

deployment:
  replicaCount: 1
  elasticGrokFilter: axel
  memory: 512Mi

container:
  axel:
    image:
      pullPolicy: Always
      tag: 

imagePullSecrets:
  - name: regcred

ingressroute:
  hostName: axel.localhost
  bksHostName: base.env.url # This should be overridden and set to your environment's base hostname.
  pathPrefix: "axel"

# Environment-specific backwards-compatible service name
vip:
  name: legacy-axel-vip

environment:
  axel:
    home: /usr/local/tomcat
    variables:
      _default_config_maps:
        - axel-configmap-default
      config_maps:
        # Nothing yet. Override to supply your own values.
      secrets:
        - axel-secrets
    secretVolumes:
      certs:
        secretName: axel-certs
        mountPath: /etc/axel/certs

fileMounts:
  configMaps:
    - ref:
        configMap:
          name: axel-default-log-config
      dst:
      - mountPath: /usr/local/tomcat/conf/log4j.xml
        subPath: log4j.xml
      - mountPath: /usr/local/tomcat/conf/log4j2.xml
        subPath: log4j2.xml
      - mountPath: /usr/local/tomcat/conf/logging.properties
        subPath: logging.properties
