repository: docker.drift.inera.se/ntjp/
  axel:
    image:
      tag: 

environment:
  axel:
    variables:
      _default_config_maps:
        - axel-configmap-default
      config_maps:
        # Nothing yet. Override to supply your own values.
      secrets:
        # Nothing yet. Override to supply your own values.


    