namespace: ntjp

deployment:
  axel:
    name: axel
    replicaCount: 1
  mongo:
    name: axel-mongodb

container:
  axel:
    image:
      name: axel
      pullPolicy: always
  mongo:
    image:
      name: mongodb
      pullPolicy: always

service:
  axel:
    type: ClusterIP
    port: 8082
  mongo:
    type: ClusterIP
    port: 27017

environment:
  axel:
    variables:
      _default_config_maps:
        - axel-configmap-default
      config_maps:
        # Nothing yet. Override to supply your own values.
      secrets:
        # Nothing yet.
  mongo:
    # Nothing yet.


    