repository: docker.drift.inera.se/ntjp/

deployment:
  replicaCount: 1
  elasticGrokFilter: axel

container:
  axel:
    image:
      pullPolicy: Always
      tag: 

imagePullSecrets:
  - name: regcred


ingressroute:
  hostName: axel.localhost
  pathPrefix: "axel"

environment:
  axel:
    home: /usr/local/tomcat
    variables:
      _default_config_maps:
        - axel-configmap-default
      config_maps:
        # Nothing yet. Override to supply your own values.
      secrets:
        - axel-secrets
    secretVolumes:
      certs:
        secretName: axel-certs
        mountPath: /etc/axel/certs


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi